
spring:
  # 连接池信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123123123

    # jpa 配置
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

      #热部署
  thymeleaf:
    cache: false

# 设置日志
logging:
  level:
    root: info
    com.weiwu.blog: debug
  file:
    name: log/blog-dev.log

server:
  port: 8080
